#!/bin/bash

#SBATCH --job-name=tienAlex   ### Job Name

#SBATCH --output=chess%j.out  ### File in which to store job output

#SBATCH --error=chess%j.err   ### File in which to store job error messages

#SBATCH --partition=short      ### Quality of Service (like a queue in PBS)

#SBATCH --time=00:10:00     ### Wall clock time limit in Days-HH:MM:SS

#SBATCH --nodes=1             ### Node count required for the job

#SBATCH --ntasks-per-node=28   ### Nuber of tasks to be launched per Node

#SBATCH --cpus-per-task=1     ### Number of threads per task (OMP threads)

#SBATCH --account=cis431_531  ### Account used for job submission

export OMP_NUM_THREADS=1

module load openmp/2.1
../main


